version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    restart: always
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    volumes:
      - ./docker/dynamodb:/data
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
      - AWS_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - DYNAMODB_TABLE_PREFIX=LogoQuiz
      - APP_SALT=mysalt
      - APP_SESSION_SECRET=mysecret
    depends_on:
      - dynamodb-local
    networks:
      - app-network
    restart: on-failure

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - api
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge
